name: CI-CD Render Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image (test build only)
        run: docker build -t test-image .

      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/v1/services/srv-d6e9ksq4d50c73bdd7g0/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json"